CREATE OR REPLACE PROCEDURE humanresources.uspupdateemployeehireinfo(IN par_businessentityid INTEGER, IN par_jobtitle VARCHAR, IN par_hiredate TIMESTAMP WITHOUT TIME ZONE, IN par_ratechangedate TIMESTAMP WITHOUT TIME ZONE, IN par_rate NUMERIC, IN par_payfrequency SMALLINT, IN par_currentflag dbo.flag)
AS 
$BODY$
DECLARE
    usplogerror$par_ErrorLogID INTEGER;
    usplogerror$ReturnCode INTEGER;
BEGIN
    /* [7744 - Severity INFO - This conversion uses machine learning models that generate predictions based on patterns in data. Output generated by a machine learning model is probabilistic and should be evaluated for accuracy as appropriate for your use case, including by employing human review of such output.] */
    /* EXECUTE AS CALLER is not supported in Aurora PostgreSQL */
    /* Aurora PostgreSQL uses SET ROLE for context switching, but EXECUTE AS CALLER */
    /* which executes in the caller's security context is the default behavior */
    /* No equivalent statement needed as this is default behavior in PostgreSQL */
    
    /* vvv ---- Beginning of statement generated using GenAI. ---- vvv */
    SELECT 1;
    /* ^^^ ---- End of statement generated using GenAI. ---- ^^^ */
    BEGIN
        /*
        [7807 - Severity CRITICAL - PostgreSQL does not support explicit transaction management commands such as BEGIN TRAN, SAVE TRAN in functions. Convert your source code manually.]
        BEGIN TRANSACTION;
        */
        UPDATE humanresources.employee
        SET jobtitle = par_JobTitle,
            hiredate = par_HireDate,
            currentflag = par_CurrentFlag
        WHERE businessentityid = par_BusinessEntityID;
        INSERT INTO humanresources.employeepayhistory (businessentityid,
            ratechangedate,
            rate,
            payfrequency)
        VALUES (par_BusinessEntityID, par_RateChangeDate, par_Rate, par_PayFrequency);
        /*
        [7615 - Severity CRITICAL - Your code ends a transaction inside a block with exception handlers. Revise your code to move transaction control to the application side and try again.]
        COMMIT TRANSACTION;
        */
        EXCEPTION
            WHEN OTHERS THEN
                /* Rollback any active or uncommittable transactions before */
                /* inserting information in the ErrorLog */
                
                /* [7744 - Severity INFO - This conversion uses machine learning models that generate predictions based on patterns in data. Output generated by a machine learning model is probabilistic and should be evaluated for accuracy as appropriate for your use case, including by employing human review of such output.] */
                /* PostgreSQL does not have an equivalent to @@TRANCOUNT */
                /* This code checks transaction state and rolls back if in a transaction */
                /* In PostgreSQL, we can check if we're in a transaction block using current_setting */
                /* However, since we cannot use DO blocks and the conversion rule prohibits aws_sqlserver_ext, */
                /* we'll use a conditional ROLLBACK which will error if not in a transaction */
                /* The closest equivalent is to attempt ROLLBACK which will only succeed if in a transaction */
                
                /* vvv ---- Beginning of statement generated using GenAI. ---- vvv */
                ROLLBACK WORK;
                /* ^^^ ---- End of statement generated using GenAI. ---- ^^^ */
                CALL dbo.usplogerror(par_ErrorLogID => usplogerror$par_ErrorLogID, return_code => usplogerror$ReturnCode);
    END;
END;
$BODY$
LANGUAGE plpgsql;