CREATE OR REPLACE PROCEDURE humanresources.uspupdateemployeelogin(IN par_businessentityid INTEGER, IN par_organizationnode VARCHAR, IN par_loginid VARCHAR, IN par_jobtitle VARCHAR, IN par_hiredate TIMESTAMP WITHOUT TIME ZONE, IN par_currentflag dbo.flag)
AS 
$BODY$
DECLARE
    usplogerror$par_ErrorLogID INTEGER;
    usplogerror$ReturnCode INTEGER;
BEGIN
    /* [7744 - Severity INFO - This conversion uses machine learning models that generate predictions based on patterns in data. Output generated by a machine learning model is probabilistic and should be evaluated for accuracy as appropriate for your use case, including by employing human review of such output.] */
    /* Note: Aurora PostgreSQL does not have a direct equivalent to MSSQL's EXECUTE AS CALLER. */
    /* EXECUTE AS CALLER in MSSQL specifies that the code executes in the context of the caller. */
    /* In PostgreSQL, this is the default behavior for functions and procedures. */
    /* No explicit statement is needed as PostgreSQL functions execute with caller's privileges by default. */
    
    /* vvv ---- Beginning of statement generated using GenAI. ---- vvv */
    SELECT 1
        WHERE FALSE;
    /* ^^^ ---- End of statement generated using GenAI. ---- ^^^ */
    BEGIN
        /* [7744 - Severity INFO - This conversion uses machine learning models that generate predictions based on patterns in data. Output generated by a machine learning model is probabilistic and should be evaluated for accuracy as appropriate for your use case, including by employing human review of such output.] */
        /* vvv ---- Beginning of statement generated using GenAI. ---- vvv */
        UPDATE humanresources.employee
        SET organizationnode = /*
        [7657 - Severity CRITICAL - PostgreSQL doesn't support the hierarchyid data type. Convert your source code manually to make sure that you store data of the hierarchyid data type using a compatible type in PostgreSQL or a composite type.]
        [OrganizationNode]
        */
        par_OrganizationNode,
            loginid = par_LoginID,
            jobtitle = par_JobTitle,
            hiredate = par_HireDate,
            currentflag = par_CurrentFlag
        WHERE businessentityid = par_BusinessEntityID;
        /* ^^^ ---- End of statement generated using GenAI. ---- ^^^ */
        BEGIN
        END;
        EXCEPTION
            WHEN OTHERS THEN
                CALL dbo.usplogerror(par_ErrorLogID => usplogerror$par_ErrorLogID, return_code => usplogerror$ReturnCode);
    END;
END;
$BODY$
LANGUAGE plpgsql;