-- Person.Address -> person.address
-- geography SpatialLocation -> text (WKT); loaded via a custom step using STAsText().
CREATE TABLE person.address (
    addressid       integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    addressline1    varchar(60) NOT NULL,
    addressline2    varchar(60),
    city            varchar(30) NOT NULL,
    stateprovinceid integer NOT NULL,
    postalcode      varchar(15) NOT NULL,
    spatiallocation text,
    rowguid         uuid NOT NULL DEFAULT gen_random_uuid(),
    modifieddate    timestamp NOT NULL DEFAULT now(),
    CONSTRAINT pk_address PRIMARY KEY (addressid)
);
CREATE UNIQUE INDEX ak_address_rowguid ON person.address (rowguid);
CREATE UNIQUE INDEX ix_address_full ON person.address (addressline1, addressline2, city, stateprovinceid, postalcode);
CREATE INDEX ix_address_stateprovinceid ON person.address (stateprovinceid);
ALTER TABLE person.address ADD CONSTRAINT fk_address_stateprovince
    FOREIGN KEY (stateprovinceid) REFERENCES person.stateprovince (stateprovinceid);
