-- Person.AddressType -> person.addresstype
CREATE TABLE person.addresstype (
    addresstypeid integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          varchar(50) NOT NULL,
    rowguid       uuid NOT NULL DEFAULT gen_random_uuid(),
    modifieddate  timestamp NOT NULL DEFAULT now(),
    CONSTRAINT pk_addresstype PRIMARY KEY (addresstypeid)
);
CREATE UNIQUE INDEX ak_addresstype_name ON person.addresstype (name);
CREATE UNIQUE INDEX ak_addresstype_rowguid ON person.addresstype (rowguid);
