-- Person.BusinessEntity -> person.businessentity
CREATE TABLE person.businessentity (
    businessentityid integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rowguid          uuid NOT NULL DEFAULT gen_random_uuid(),
    modifieddate     timestamp NOT NULL DEFAULT now(),
    CONSTRAINT pk_businessentity PRIMARY KEY (businessentityid)
);
CREATE UNIQUE INDEX ak_businessentity_rowguid ON person.businessentity (rowguid);
