-- Person.ContactType -> person.contacttype
CREATE TABLE person.contacttype (
    contacttypeid integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          varchar(50) NOT NULL,
    modifieddate  timestamp NOT NULL DEFAULT now(),
    CONSTRAINT pk_contacttype PRIMARY KEY (contacttypeid)
);
CREATE UNIQUE INDEX ak_contacttype_name ON person.contacttype (name);
