-- Person.EmailAddress -> person.emailaddress
CREATE TABLE person.emailaddress (
    businessentityid integer NOT NULL,
    emailaddressid   integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    emailaddress     varchar(50),
    rowguid          uuid NOT NULL DEFAULT gen_random_uuid(),
    modifieddate     timestamp NOT NULL DEFAULT now(),
    CONSTRAINT pk_emailaddress PRIMARY KEY (businessentityid, emailaddressid)
);
CREATE INDEX ix_emailaddress_emailaddress ON person.emailaddress (emailaddress);
ALTER TABLE person.emailaddress ADD CONSTRAINT fk_emailaddress_person
    FOREIGN KEY (businessentityid) REFERENCES person.person (businessentityid);
