-- Person.PhoneNumberType -> person.phonenumbertype
CREATE TABLE person.phonenumbertype (
    phonenumbertypeid integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              varchar(50) NOT NULL,
    modifieddate      timestamp NOT NULL DEFAULT now(),
    CONSTRAINT pk_phonenumbertype PRIMARY KEY (phonenumbertypeid)
);
