-- Person.StateProvince -> person.stateprovince
-- NOTE: the source FK StateProvince.TerritoryID -> Sales.SalesTerritory is DROPPED because the
-- Sales schema is out of scope for this run; territoryid is retained as a plain column.
CREATE TABLE person.stateprovince (
    stateprovinceid         integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stateprovincecode       char(3) NOT NULL,
    countryregioncode       varchar(3) NOT NULL,
    isonlystateprovinceflag boolean NOT NULL DEFAULT true,
    name                    varchar(50) NOT NULL,
    territoryid             integer NOT NULL,
    rowguid                 uuid NOT NULL DEFAULT gen_random_uuid(),
    modifieddate            timestamp NOT NULL DEFAULT now(),
    CONSTRAINT pk_stateprovince PRIMARY KEY (stateprovinceid)
);
CREATE UNIQUE INDEX ak_stateprovince_name ON person.stateprovince (name);
CREATE UNIQUE INDEX ak_stateprovince_rowguid ON person.stateprovince (rowguid);
CREATE UNIQUE INDEX ak_stateprovince_code_country ON person.stateprovince (stateprovincecode, countryregioncode);
ALTER TABLE person.stateprovince ADD CONSTRAINT fk_stateprovince_countryregion
    FOREIGN KEY (countryregioncode) REFERENCES person.countryregion (countryregioncode);
