-- HumanResources.Department -> humanresources.department
CREATE TABLE humanresources.department (
    departmentid smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         varchar(50) NOT NULL,
    groupname    varchar(50) NOT NULL,
    modifieddate timestamp NOT NULL DEFAULT now(),
    CONSTRAINT pk_department PRIMARY KEY (departmentid)
);
CREATE UNIQUE INDEX ak_department_name ON humanresources.department (name);
