-- HumanResources.JobCandidate -> humanresources.jobcandidate  (xml Resume -> xml)
CREATE TABLE humanresources.jobcandidate (
    jobcandidateid   integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    businessentityid integer,
    resume           xml,
    modifieddate     timestamp NOT NULL DEFAULT now(),
    CONSTRAINT pk_jobcandidate PRIMARY KEY (jobcandidateid)
);
CREATE INDEX ix_jobcandidate_businessentityid ON humanresources.jobcandidate (businessentityid);
ALTER TABLE humanresources.jobcandidate ADD CONSTRAINT fk_jobcandidate_employee
    FOREIGN KEY (businessentityid) REFERENCES humanresources.employee (businessentityid);
