-- HumanResources.Shift -> humanresources.shift  (tinyint -> smallint; time -> time)
CREATE TABLE humanresources.shift (
    shiftid      smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         varchar(50) NOT NULL,
    starttime    time NOT NULL,
    endtime      time NOT NULL,
    modifieddate timestamp NOT NULL DEFAULT now(),
    CONSTRAINT pk_shift PRIMARY KEY (shiftid)
);
CREATE UNIQUE INDEX ak_shift_name ON humanresources.shift (name);
CREATE UNIQUE INDEX ak_shift_starttime_endtime ON humanresources.shift (starttime, endtime);
