-- Converted from Oracle DEMO.ADDRESSES -> PostgreSQL demo.addresses
-- Decisions:
--   NUMBER(19,0) IDENTITY PK -> bigint GENERATED BY DEFAULT AS IDENTITY (non-portable-constructs.md → Sequences/identity)
--   NUMBER(1,0) 0/1 flag     -> smallint + CHECK (col IN (0,1))  [NOT boolean: app stores 0/1, data copied verbatim]
--   SYS_C* unique index      -> dropped; PRIMARY KEY creates its own unique index
--   FOREIGN KEY              -> deferred to --post-data (applied after the data load)

CREATE TABLE demo.addresses (
    id             bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1 MINVALUE 1 CACHE 20) NOT NULL,
    address_line1  varchar(255),
    address_line2  varchar(255),
    address_type   varchar(255),
    city           varchar(255),
    state          varchar(255),
    postal_code    varchar(255),
    country        varchar(255),
    customer_id    bigint,
    is_default     smallint DEFAULT 0,
    CONSTRAINT pk_addresses PRIMARY KEY (id),
    CONSTRAINT ck_addresses_is_default CHECK (is_default IN (0,1))
);

-- deferred (post-data)
ALTER TABLE demo.addresses
    ADD CONSTRAINT fk_addresses_customer FOREIGN KEY (customer_id)
    REFERENCES demo.customers (id);
