-- DEMO.ADDRESSES -> demo.addresses
-- NUMBER(19,0) IDENTITY -> bigint GENERATED BY DEFAULT AS IDENTITY (PG identity requires an integer type).
-- NUMBER(1,0) IS_DEFAULT -> smallint + CHECK (preserves the 0/1 domain; data copied verbatim).
-- FK to customers is deferred to the post-data pass.
CREATE TABLE demo.addresses (
    id            bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1) NOT NULL,
    address_line1 varchar(255),
    address_line2 varchar(255),
    address_type  varchar(255),
    city          varchar(255),
    state         varchar(255),
    postal_code   varchar(255),
    country       varchar(255),
    customer_id   bigint,
    is_default    smallint DEFAULT 0,
    CONSTRAINT addresses_pk PRIMARY KEY (id),
    CONSTRAINT addresses_is_default_chk CHECK (is_default IN (0, 1))
);

ALTER TABLE demo.addresses ADD CONSTRAINT fk_addresses_customer
    FOREIGN KEY (customer_id) REFERENCES demo.customers (id);
