-- Converted from Oracle DEMO.BOOKS -> PostgreSQL demo.books
-- Decisions:
--   NUMBER(19,0) IDENTITY PK -> bigint GENERATED BY DEFAULT AS IDENTITY
--   NUMBER(10,0) YEAR        -> bigint (10 digits exceed int32) (non-portable-constructs.md → Datatypes)
--   DATE PUBLISH_DATE        -> timestamp(0), NOT date (Oracle DATE carries time-of-day)
--   TIMESTAMP(6)             -> timestamp(6)
--   SYS_C* unique index      -> dropped (PK provides it)
--
--   FULL-TEXT SEARCH (Manual redesign — approved decision: PRESERVE search):
--     Oracle Text domain index  BOOKS_TEXT_IDX ON BOOKS(SEARCH_TEXT)
--       INDEXTYPE IS CTXSYS.CONTEXT PARAMETERS ('SYNC (ON COMMIT)')
--     -> PostgreSQL GIN full-text index over to_tsvector('english', search_text).
--        GIN is maintained transactionally by PG, so Oracle's explicit
--        "SYNC (ON COMMIT)" has no counterpart and is simply dropped.
--        Rewrite any CONTAINS(search_text, :q) predicate as:
--          WHERE to_tsvector('english', coalesce(search_text,'')) @@ to_tsquery('english', :q)
--     Ref: non-portable-constructs.md → Indexes (Oracle Text domain index)
--
--   TRG_BOOK_SEARCH_TEXT -> PL/pgSQL trigger function + CREATE TRIGGER (deferred to --post-data).
--     NVL -> COALESCE.  The function is pre-data; the CREATE TRIGGER binding is post-data so
--     the trigger cannot rewrite rows during the load.

CREATE TABLE demo.books (
    id            bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1 MINVALUE 1 CACHE 20) NOT NULL,
    title         varchar(255),
    author        varchar(255),
    isbn          varchar(255),
    description   varchar(1000),
    publish_date  timestamp(0),
    year          bigint,
    created_on    timestamp(6),
    updated_on    timestamp(6),
    created_by    varchar(255),
    genre_id      bigint,
    publisher_id  bigint,
    book_type_id  bigint,
    search_text   varchar(1000),
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE INDEX idx_books_search    ON demo.books (search_text);
CREATE INDEX idx_books_isbn      ON demo.books (isbn);
CREATE INDEX idx_books_genre     ON demo.books (genre_id);
CREATE INDEX idx_books_publisher ON demo.books (publisher_id);

-- Oracle Text CONTEXT index -> PostgreSQL GIN full-text index
CREATE INDEX books_text_idx ON demo.books
    USING gin (to_tsvector('english', coalesce(search_text, '')));

-- Trigger FUNCTION (pre-data). Mirrors Oracle TRG_BOOK_SEARCH_TEXT.
CREATE OR REPLACE FUNCTION demo.trg_book_search_text_fn()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.search_text := lower(NEW.title) || ' ' ||
                       lower(coalesce(NEW.author, '')) || ' ' ||
                       lower(coalesce(NEW.isbn, ''));
    RETURN NEW;
END;
$$;

-- deferred (post-data)
ALTER TABLE demo.books
    ADD CONSTRAINT fk_books_book_type FOREIGN KEY (book_type_id)
    REFERENCES demo.book_types (id);
ALTER TABLE demo.books
    ADD CONSTRAINT fk_books_genre FOREIGN KEY (genre_id)
    REFERENCES demo.genres (id);
ALTER TABLE demo.books
    ADD CONSTRAINT fk_books_publisher FOREIGN KEY (publisher_id)
    REFERENCES demo.publishers (id);

CREATE TRIGGER trg_book_search_text
    BEFORE INSERT OR UPDATE OF title, author, isbn ON demo.books
    FOR EACH ROW
    EXECUTE FUNCTION demo.trg_book_search_text_fn();
