-- DEMO.BOOKS -> demo.books
-- DATE -> timestamp(0) (Oracle DATE carries time-of-day). NUMBER(10,0) YEAR -> bigint (10 digits exceed int32).
-- Oracle Text CONTEXT index BOOKS_TEXT_IDX -> PostgreSQL GIN full-text index on to_tsvector.
-- BEFORE-row trigger TRG_BOOK_SEARCH_TEXT -> PL/pgSQL trigger (NVL -> COALESCE); CREATE TRIGGER deferred to post-data.
CREATE TABLE demo.books (
    id           bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1) NOT NULL,
    title        varchar(255),
    author       varchar(255),
    isbn         varchar(255),
    description  varchar(1000),
    publish_date timestamp(0),
    year         bigint,
    created_on   timestamp(6),
    updated_on   timestamp(6),
    created_by   varchar(255),
    genre_id     bigint,
    publisher_id bigint,
    book_type_id bigint,
    search_text  varchar(1000),
    CONSTRAINT books_pk PRIMARY KEY (id)
);

CREATE INDEX idx_books_search    ON demo.books (search_text);
CREATE INDEX idx_books_isbn      ON demo.books (isbn);
CREATE INDEX idx_books_genre     ON demo.books (genre_id);
CREATE INDEX idx_books_publisher ON demo.books (publisher_id);
-- Oracle Text (CTXSYS.CONTEXT, SYNC ON COMMIT) -> GIN full-text index.
CREATE INDEX books_text_idx ON demo.books USING gin (to_tsvector('english', coalesce(search_text, '')));

-- Foreign keys (deferred to post-data).
ALTER TABLE demo.books ADD CONSTRAINT fk_books_book_type FOREIGN KEY (book_type_id) REFERENCES demo.book_types (id);
ALTER TABLE demo.books ADD CONSTRAINT fk_books_genre      FOREIGN KEY (genre_id)      REFERENCES demo.genres (id);
ALTER TABLE demo.books ADD CONSTRAINT fk_books_publisher  FOREIGN KEY (publisher_id)  REFERENCES demo.publishers (id);

-- search_text maintenance: trigger function (pre-data) + trigger binding (deferred to post-data).
CREATE OR REPLACE FUNCTION demo.trg_book_search_text() RETURNS trigger AS $$
BEGIN
  NEW.search_text := lower(NEW.title) || ' ' ||
                     lower(coalesce(NEW.author, '')) || ' ' ||
                     lower(coalesce(NEW.isbn, ''));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_book_search_text
  BEFORE INSERT OR UPDATE OF title, author, isbn ON demo.books
  FOR EACH ROW EXECUTE FUNCTION demo.trg_book_search_text();
