-- Converted from Oracle DEMO.BOOK_TYPES -> PostgreSQL demo.book_types
-- Decisions: NUMBER(19,0) IDENTITY PK -> bigint IDENTITY; SYS_C* unique index dropped (PK provides it).

CREATE TABLE demo.book_types (
    id           bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1 MINVALUE 1 CACHE 20) NOT NULL,
    created_on   timestamp(6),
    description  varchar(255),
    name         varchar(255) NOT NULL,
    updated_on   timestamp(6),
    CONSTRAINT pk_book_types PRIMARY KEY (id)
);
