-- DEMO.CONDITIONS -> demo.conditions
CREATE TABLE demo.conditions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1) NOT NULL,
    created_on  timestamp(6),
    description varchar(255),
    name        varchar(255) NOT NULL,
    updated_on  timestamp(6),
    CONSTRAINT conditions_pk PRIMARY KEY (id)
);
