-- Converted from Oracle DEMO.CUSTOMERS -> PostgreSQL demo.customers
-- Decisions:
--   NUMBER(19,0) IDENTITY PK -> bigint GENERATED BY DEFAULT AS IDENTITY
--   NUMBER(1,0) 0/1 flags    -> smallint + CHECK (col IN (0,1))  [4 flags; kept 0/1 not boolean for verbatim copy]
--   DATE DATE_OF_BIRTH       -> timestamp(0), NOT date (Oracle DATE carries time-of-day)
--   SYS_C* unique index      -> dropped (PK provides it)
--   Note: USERNAME/EMAIL carry no unique constraint in the source — none added (parity preserved).

CREATE TABLE demo.customers (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1 MINVALUE 1 CACHE 20) NOT NULL,
    username             varchar(255),
    email                varchar(255),
    first_name           varchar(255),
    last_name            varchar(255),
    phone_number         varchar(255),
    password_hash        varchar(255),
    sub                  varchar(255),
    date_of_birth        timestamp(0),
    created_on           timestamp(6),
    email_verified       smallint DEFAULT 0,
    role                 varchar(255),
    account_expired      smallint DEFAULT 0,
    credentials_expired  smallint DEFAULT 0,
    account_locked       smallint DEFAULT 0,
    last_login           timestamp(6),
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT ck_customers_account_expired     CHECK (account_expired IN (0,1)),
    CONSTRAINT ck_customers_account_locked      CHECK (account_locked IN (0,1)),
    CONSTRAINT ck_customers_credentials_expired CHECK (credentials_expired IN (0,1)),
    CONSTRAINT ck_customers_email_verified      CHECK (email_verified IN (0,1))
);
