-- DEMO.CUSTOMERS -> demo.customers
-- NUMBER(1,0) flags -> smallint + CHECK (0,1). DATE_OF_BIRTH DATE -> timestamp(0).
CREATE TABLE demo.customers (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1) NOT NULL,
    username            varchar(255),
    email               varchar(255),
    first_name          varchar(255),
    last_name           varchar(255),
    phone_number        varchar(255),
    password_hash       varchar(255),
    sub                 varchar(255),
    date_of_birth       timestamp(0),
    created_on          timestamp(6),
    email_verified      smallint DEFAULT 0,
    role                varchar(255),
    account_expired     smallint DEFAULT 0,
    credentials_expired smallint DEFAULT 0,
    account_locked      smallint DEFAULT 0,
    last_login          timestamp(6),
    CONSTRAINT customers_pk PRIMARY KEY (id),
    CONSTRAINT customers_account_expired_chk     CHECK (account_expired IN (0, 1)),
    CONSTRAINT customers_account_locked_chk      CHECK (account_locked IN (0, 1)),
    CONSTRAINT customers_credentials_expired_chk CHECK (credentials_expired IN (0, 1)),
    CONSTRAINT customers_email_verified_chk      CHECK (email_verified IN (0, 1))
);
