-- DEMO.GENRES -> demo.genres
CREATE TABLE demo.genres (
    id          bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1) NOT NULL,
    created_on  timestamp(6),
    description varchar(255),
    name        varchar(255) NOT NULL,
    updated_on  timestamp(6),
    CONSTRAINT genres_pk PRIMARY KEY (id)
);
