-- Converted from Oracle DEMO.LISTINGS -> PostgreSQL demo.listings
-- Decisions:
--   NUMBER(19,0) IDENTITY PK -> bigint GENERATED BY DEFAULT AS IDENTITY
--   NUMBER(38,2) PRICE       -> numeric(38,2) (exact decimal money; never float)
--   NUMBER(10,0) QUANTITY/STATUS -> bigint (10 digits exceed int32)
--   NUMBER(1,0) 0/1 flags    -> smallint + CHECK (col IN (0,1))
--   SYS_C* unique index      -> dropped (PK provides it)
--   4 FOREIGN KEYs           -> deferred to --post-data

CREATE TABLE demo.listings (
    id              bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1 MINVALUE 1 CACHE 20) NOT NULL,
    book_id         bigint NOT NULL,
    seller_id       bigint NOT NULL,
    price           numeric(38,2) NOT NULL,
    quantity        bigint DEFAULT 1 NOT NULL,
    condition_id    bigint,
    status          bigint DEFAULT 0 NOT NULL,
    listing_type    varchar(20) NOT NULL,
    admin_notes     varchar(1000),
    processed_at    timestamp(6),
    processed_by    bigint,
    is_featured     smallint DEFAULT 0,
    is_bestseller   smallint DEFAULT 0,
    is_new_arrival  smallint DEFAULT 0,
    created_on      timestamp(6) NOT NULL,
    updated_on      timestamp(6),
    CONSTRAINT pk_listings PRIMARY KEY (id),
    CONSTRAINT ck_listings_is_featured    CHECK (is_featured IN (0,1)),
    CONSTRAINT ck_listings_is_bestseller  CHECK (is_bestseller IN (0,1)),
    CONSTRAINT ck_listings_is_new_arrival CHECK (is_new_arrival IN (0,1))
);

CREATE INDEX idx_listings_status      ON demo.listings (status);
CREATE INDEX idx_listings_seller      ON demo.listings (seller_id);
CREATE INDEX idx_listings_book        ON demo.listings (book_id);
CREATE INDEX idx_listings_type        ON demo.listings (listing_type);
CREATE INDEX idx_listings_type_status ON demo.listings (listing_type, status);

-- deferred (post-data)
ALTER TABLE demo.listings
    ADD CONSTRAINT fk_listings_book FOREIGN KEY (book_id)
    REFERENCES demo.books (id);
ALTER TABLE demo.listings
    ADD CONSTRAINT fk_listings_seller FOREIGN KEY (seller_id)
    REFERENCES demo.customers (id);
ALTER TABLE demo.listings
    ADD CONSTRAINT fk_listings_condition FOREIGN KEY (condition_id)
    REFERENCES demo.conditions (id);
ALTER TABLE demo.listings
    ADD CONSTRAINT fk_listings_processed_by FOREIGN KEY (processed_by)
    REFERENCES demo.customers (id);
