-- DEMO.ORDER_ITEMS -> demo.order_items
CREATE TABLE demo.order_items (
    id         bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1) NOT NULL,
    order_id   bigint,
    book_id    bigint,
    listing_id bigint,
    quantity   bigint NOT NULL,
    book_price numeric(38,2) NOT NULL,
    discount   numeric(38,2),
    CONSTRAINT order_items_pk PRIMARY KEY (id)
);

CREATE INDEX idx_order_items_order ON demo.order_items (order_id);

ALTER TABLE demo.order_items ADD CONSTRAINT fk_order_items_order   FOREIGN KEY (order_id)   REFERENCES demo.orders (id);
ALTER TABLE demo.order_items ADD CONSTRAINT fk_order_items_book    FOREIGN KEY (book_id)    REFERENCES demo.books (id);
ALTER TABLE demo.order_items ADD CONSTRAINT fk_order_items_listing FOREIGN KEY (listing_id) REFERENCES demo.listings (id);
