-- Converted from Oracle DEMO.ORDER_ITEMS -> PostgreSQL demo.order_items
-- Decisions:
--   NUMBER(19,0) IDENTITY PK -> bigint GENERATED BY DEFAULT AS IDENTITY
--   NUMBER(10,0) QUANTITY    -> bigint; NUMBER(38,2) money -> numeric(38,2)
--   SYS_C* unique index      -> dropped (PK provides it)
--   3 FOREIGN KEYs           -> deferred to --post-data

CREATE TABLE demo.order_items (
    id          bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1 MINVALUE 1 CACHE 20) NOT NULL,
    order_id    bigint,
    book_id     bigint,
    listing_id  bigint,
    quantity    bigint NOT NULL,
    book_price  numeric(38,2) NOT NULL,
    discount    numeric(38,2),
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE INDEX idx_order_items_order ON demo.order_items (order_id);

-- deferred (post-data)
ALTER TABLE demo.order_items
    ADD CONSTRAINT fk_order_items_order FOREIGN KEY (order_id)
    REFERENCES demo.orders (id);
ALTER TABLE demo.order_items
    ADD CONSTRAINT fk_order_items_book FOREIGN KEY (book_id)
    REFERENCES demo.books (id);
ALTER TABLE demo.order_items
    ADD CONSTRAINT fk_order_items_listing FOREIGN KEY (listing_id)
    REFERENCES demo.listings (id);
