-- DEMO.ORDERS -> demo.orders
-- Monetary NUMBER(38,2) -> numeric(38,2); DATE columns -> timestamp(0). No FKs defined on the source table.
CREATE TABLE demo.orders (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1) NOT NULL,
    customer_id         bigint,
    address_id          bigint,
    created_on          timestamp(6) NOT NULL,
    updated_on          timestamp(6),
    status              varchar(255),
    total_amount        numeric(38,2),
    discount            numeric(38,2),
    tax                 numeric(38,2),
    shipping_cost       numeric(38,2),
    payment_method      varchar(255),
    payment_status      varchar(255),
    shipped_date        timestamp(0),
    delivered_date      timestamp(0),
    cancelled_date      timestamp(0),
    cancellation_reason varchar(255),
    tracking_number     varchar(255),
    notes               varchar(1000),
    CONSTRAINT orders_pk PRIMARY KEY (id)
);

CREATE INDEX idx_orders_customer ON demo.orders (customer_id);
CREATE INDEX idx_orders_status   ON demo.orders (status);
