-- DEMO.PASSWORD_RESET_TOKENS -> demo.password_reset_tokens
-- Identity starts at 1 (source START WITH 1). USED NUMBER(1,0) -> smallint + CHECK. FK deferred.
CREATE TABLE demo.password_reset_tokens (
    id          bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    token       varchar(255),
    customer_id bigint,
    expiry_date timestamp(6),
    used        smallint DEFAULT 0,
    CONSTRAINT password_reset_tokens_pk PRIMARY KEY (id),
    CONSTRAINT password_reset_tokens_used_chk CHECK (used IN (0, 1))
);

ALTER TABLE demo.password_reset_tokens ADD CONSTRAINT fk_password_reset_customer
    FOREIGN KEY (customer_id) REFERENCES demo.customers (id);
