-- Converted from Oracle DEMO.PASSWORD_RESET_TOKENS -> PostgreSQL demo.password_reset_tokens
-- Decisions:
--   NUMBER(19,0) IDENTITY PK -> bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 — differs
--     from the other tables' 101; preserved from the source sequence definition)
--   NUMBER(1,0) USED flag    -> smallint + CHECK (used IN (0,1))
--   EXPIRY_DATE is TIMESTAMP(6) in the source (despite the name) -> timestamp(6)
--   SYS_C* unique index      -> dropped (PK provides it); FK deferred to --post-data

CREATE TABLE demo.password_reset_tokens (
    id           bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 CACHE 20) NOT NULL,
    token        varchar(255),
    customer_id  bigint,
    expiry_date  timestamp(6),
    used         smallint DEFAULT 0,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id),
    CONSTRAINT ck_password_reset_tokens_used CHECK (used IN (0,1))
);

-- deferred (post-data)
ALTER TABLE demo.password_reset_tokens
    ADD CONSTRAINT fk_password_reset_customer FOREIGN KEY (customer_id)
    REFERENCES demo.customers (id);
