-- Converted from Oracle DEMO.PUBLISHERS -> PostgreSQL demo.publishers
-- Decisions: NUMBER(19,0) IDENTITY PK -> bigint IDENTITY; SYS_C* unique index dropped (PK provides it).

CREATE TABLE demo.publishers (
    id           bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1 MINVALUE 1 CACHE 20) NOT NULL,
    created_on   timestamp(6),
    description  varchar(255),
    name         varchar(255) NOT NULL,
    updated_on   timestamp(6),
    website      varchar(255),
    CONSTRAINT pk_publishers PRIMARY KEY (id)
);
