-- DEMO.PUBLISHERS -> demo.publishers
CREATE TABLE demo.publishers (
    id          bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1) NOT NULL,
    created_on  timestamp(6),
    description varchar(255),
    name        varchar(255) NOT NULL,
    updated_on  timestamp(6),
    website     varchar(255),
    CONSTRAINT publishers_pk PRIMARY KEY (id)
);
