-- Converted from Oracle DEMO.SHOPPING_CART_ITEMS -> PostgreSQL demo.shopping_cart_items
-- Decisions:
--   NUMBER(19,0) IDENTITY PK -> bigint GENERATED BY DEFAULT AS IDENTITY
--   NUMBER(10,0) QUANTITY    -> bigint; NUMBER(1,0) flag -> smallint + CHECK IN (0,1)
--   SYS_C* unique index      -> dropped (PK provides it); 3 FKs deferred to --post-data

CREATE TABLE demo.shopping_cart_items (
    id                bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1 MINVALUE 1 CACHE 20) NOT NULL,
    customer_id       bigint,
    book_id           bigint,
    listing_id        bigint,
    quantity          bigint,
    is_wishlist_item  smallint DEFAULT 0,
    CONSTRAINT pk_shopping_cart_items PRIMARY KEY (id),
    CONSTRAINT ck_shopping_cart_items_is_wishlist CHECK (is_wishlist_item IN (0,1))
);

CREATE INDEX idx_cart_customer ON demo.shopping_cart_items (customer_id);

-- deferred (post-data)
ALTER TABLE demo.shopping_cart_items
    ADD CONSTRAINT fk_cart_items_customer FOREIGN KEY (customer_id)
    REFERENCES demo.customers (id);
ALTER TABLE demo.shopping_cart_items
    ADD CONSTRAINT fk_cart_items_book FOREIGN KEY (book_id)
    REFERENCES demo.books (id);
ALTER TABLE demo.shopping_cart_items
    ADD CONSTRAINT fk_cart_items_listing FOREIGN KEY (listing_id)
    REFERENCES demo.listings (id);
