-- DEMO.SHOPPING_CART_ITEMS -> demo.shopping_cart_items
-- IS_WISHLIST_ITEM NUMBER(1,0) -> smallint + CHECK. FKs deferred.
CREATE TABLE demo.shopping_cart_items (
    id               bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1) NOT NULL,
    customer_id      bigint,
    book_id          bigint,
    listing_id       bigint,
    quantity         bigint,
    is_wishlist_item smallint DEFAULT 0,
    CONSTRAINT shopping_cart_items_pk PRIMARY KEY (id),
    CONSTRAINT shopping_cart_items_is_wishlist_chk CHECK (is_wishlist_item IN (0, 1))
);

CREATE INDEX idx_cart_customer ON demo.shopping_cart_items (customer_id);

ALTER TABLE demo.shopping_cart_items ADD CONSTRAINT fk_cart_items_customer FOREIGN KEY (customer_id) REFERENCES demo.customers (id);
ALTER TABLE demo.shopping_cart_items ADD CONSTRAINT fk_cart_items_book     FOREIGN KEY (book_id)     REFERENCES demo.books (id);
ALTER TABLE demo.shopping_cart_items ADD CONSTRAINT fk_cart_items_listing  FOREIGN KEY (listing_id)  REFERENCES demo.listings (id);
